stages:
  download_data:
    cmd: .\.venv_win\Scripts\python src/data/download_data.py
    deps:
      - src/data/download_data.py
    outs:
      - data/raw/oil_leakage_corrosion

  prepare_data:
    cmd: .\.venv_win\Scripts\python src/data/prepare_data.py
    deps:
      - src/data/prepare_data.py
      - data/raw/oil_leakage_corrosion
    outs:
      - data/prepared.lock

  train_detector:
    cmd: .\.venv_win\Scripts\python src/vision/train_detector.py
    deps:
      - src/vision/train_detector.py
      - data/prepared.lock
    outs:
      - models/oil_leakage_yolo.pt
      - oil_project/oil_detector_experiment
